### ISSUE TITLE
Changing the styling for Konstantina's team strip

### ISSUE THREAD

**Issue by Psydwinder** [fac26/Natalia-Laura-Konstantina-Team#28]
The on all other team strips the image is left aligned and close to the green strip, but Konstantina's is also on the left. It might be worth moving the image to the right, the text and the github link to the left...

...or just making all the strips inline with one another 
 
![image](https://user-images.githubusercontent.com/101563800/193886803-4ec803af-d4fa-4d54-a8c2-34743e5cd3ef.png)

**Comment by konstantinakatmada** [comment]
great idea, glad you shared this N.

**Comment by konstantinakatmada** [comment]
On second thought, we decided to keep it on the left for aesthetic reasons, but thank you for giving us this alternative option.

**Comment by Psydwinder** [comment]
That's alright Konstantina :)
