### ISSUE TITLE
Unintentional image resizing

### ISSUE THREAD

**Issue by DFLLinton** [fac26/Natalia-Laura-Konstantina-Team#29]
Hi! It looks like when I hover over the cards within the 'Meet the Team' section, the images resize immediately. Although the difference is not large, it adds a jump to an otherwise smooth animation. The images are called 'team-member--img'.

**Comment by LauraK0** [comment]
Thanks Dom, we'll take another look and see if we can resolve the issue

**Comment by DFLLinton** [comment]
Sounds good : )
