### ISSUE TITLE
Typos on line

### ISSUE THREAD

**Issue by DFLLinton** [fac26/Natalia-Laura-Konstantina-Team#33]
Typo on line 93 of the HTML, have a look : ) thanks guys website looks great!

**Comment by ivan-unfolds** [comment]
@DFLLinton you can link to specific lines on the repo when making issues, eg https://github.com/fac26/Natalia-Laura-Konstantina-Team/blob/4c82bc5429eb0a4a09b7d586174847ba162fafcf/index.html#L93
